### ISSUE TITLE
pip uninstalls fail with "Permission denied"

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/user_workspaces_server#99]
At the top of our notebooks we `pip uninstall` a few packages, because the google collab preinstalls of these conflict with the vitessce install.

This has been working, but just today evaluating this cell:
```
!pip uninstall community flask albumentations -y # Preinstalled on Colab; Causes version conflicts.
!pip install vitessce[all]==1.0.9
```
gave me this error:
```
WARNING: Skipping community as it is not installed.
Uninstalling Flask-1.1.1:
ERROR: Exception:
Traceback (most recent call last):
  File "/hive/packages/anaconda/Anaconda3-2019.10/lib/python3.7/shutil.py", line 566, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/hive/packages/anaconda/Anaconda3-2019.10/bin/flask' -> '/tmp/pip-uninstall-z0ytjipd/flask'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/hive/packages/anaconda/Anaconda3-2019.10/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/hive/packages/anaconda/Anaconda3-2019.10/lib/python3.7/site-packages/pip/_internal/commands/uninstall.py", line 75, in run
    auto_confirm=options.yes, verbose=self.verbosity > 0,
  File "/hive/packages/anaconda/Anaconda3-2019.10/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 831, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/hive/packages/anaconda/Anaconda3-2019.10/lib/python3.7/site-packages/pip/_internal/req/req_uninstall.py", line 388, in remove
    moved.stash(path)
  File "/hive/packages/anaconda/Anaconda3-2019.10/lib/python3.7/site-packages/pip/_internal/req/req_uninstall.py", line 277, in stash
    renames(path, new_path)
  File "/hive/packages/anaconda/Anaconda3-2019.10/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 402, in renames
    shutil.move(old, new)
  File "/hive/packages/anaconda/Anaconda3-2019.10/lib/python3.7/shutil.py", line 581, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/hive/packages/anaconda/Anaconda3-2019.10/bin/flask'
```
... and later the vitessce install fails.

**Comment by jpuerto-psc** [comment]
This issue is unique to having this deployed through conda on the compute nodes. The issue is that the conda environment was created (and is managed) by the root user. Trying to pip install into this environment will fail since regular users do not have root permission.

**Comment by jpuerto-psc** [comment]
@mccalluc - my update is ready for release, seems that there are a few dependencies missing from vitessce. Had to do the following to get the notebook running:

pip install ipywidgets starlette hypercorn

**Comment by keller-mark** [comment]
> there are a few dependencies missing from vitessce

This is expected when running

```
pip install vitessce
```

but not with 

```
pip install vitessce[all]
```

because we are using `extras_require` [[1](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html?highlight=extras_require#optional-dependencies), [2](https://pip.pypa.io/en/stable/reference/requirement-specifiers/?highlight=extras), [3](https://github.com/vitessce/vitessce-python/blob/main/setup.py#L86)]
